name: 'Trivy image scan'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        id: build-image
        run: |
          docker build -t lambda-cloudwatch-slack .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: lambda-cloudwatch-slack
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
